mdapipkg/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_Due__c</fullName>
        <label>Date Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Reported__c</fullName>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapipkg/objects/Equipment_Maintenance_Item__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No spare parts meet this description or name.</errorMessage>
            <filterItems>
                <field>Product2.Replacement_Part__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Equipment Maintenance Items</relationshipLabel>
        <relationshipName>Equipment_Maintenance_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Request__c</fullName>
        <label>Maintenance Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Equipment Maintenance Items</relationshipLabel>
        <relationshipName>Equipment_Maintenance_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Equipment Maintenance Item</label>
    <nameField>
        <displayFormat>PART-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Maintenance Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/MaintenanceRequestHelper.cls
public with sharing class MaintenanceRequestHelper {
    
    public static void updateWorkOrders(List<Case> cases) {
        List<Case> newCases = new List<Case>();
        for(Case c : cases){
            //Find the shortest cycle
            Decimal shCycle = 0;
            for(Equipment_Maintenance_Item__c eq : c.Equipment_Maintenance_Items__r){
                if(shCycle == 0 || shCycle > eq.Equipment__r.Maintenance_Cycle__c)
                  shCycle = eq.Equipment__r.Maintenance_Cycle__c;
            }
            //Create a new Maintenance Request(Changed Case)
            Case newCase = new Case(
                Vehicle__c = c.Vehicle__c,
                Type = 'Routine Maintenance',
                Status = 'New'
            );
            newCase.Date_Reported__c = Date.today();
            //If none of the equipment items has a cycle today's date is set, otherwise -
            // today's date + the shortest cycle
            newCase.Date_Due__c = (shCycle == 0) ? Date.today(): 
                Date.today().addDays((Integer)shCycle);
            newCase.Subject = String.isBlank(c.Subject) ? 'Routine Maintenance Request' : c.Subject;
        	newCases.add(newCase);
		}
        if(newCases.size() > 0){
            insert newCases;
        }   
        
    }        
    
}