mdapipkg/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Inventory__c</fullName>
        <label>Current Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lifespan_Months__c</fullName>
        <label>Lifespan Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Replacement_Part__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Replacement Part</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Warehouse_SKU__c</fullName>
        <externalId>true</externalId>
        <label>Warehouse SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/WarehouseCalloutService.cls
public with sharing class WarehouseCalloutService implements Queueable, Database.AllowsCallouts{

    private static final String WAREHOUSE_URL = 'https://th-superbadge-apex.herokuapp.com/equipment';
    /* {"_id":"55d66226726b611100aaf741",
        "replacement":false,
        "quantity":5,
        "name":"Generator 1000 kW",
        "maintenanceperiod":365,
        "lifespan":120,
        "cost":5000,
        "sku":"100003"},
    */

    public void execute(QueueableContext context){
        runWarehouseEquipmentSync();
    }
    @future(callout = true)
    public static void runWarehouseEquipmentSync(){
        /*********Documentation************/
         // Instantiate a new http object
         Http h = new Http();
        
         // Instantiate a new HTTP request, specify the method (GET) as well as the endpoint
        HttpRequest req = new HttpRequest();
        req.setEndpoint(WAREHOUSE_URL);
        req.setMethod('GET');

        // Send the request, and return a response
        HttpResponse res = h.send(req);
        String data = res.getBody();
        /***********************************/
        List<Product2> equipmentList = new List<Product2>();
        List<Object> jsonResponse = (List<Object>) Json.deserializeUntyped(data);
            
        for(Object obj : jsonResponse){
            Map<String, Object> mapJson = (Map<String, Object>) obj;
            Product2 objProduct = new Product2();
            objProduct.Replacement_Part__c = true;
            objProduct.Name = (String) mapJson.get('name'); 
            objProduct.Maintenance_Cycle__c = (Integer) mapJson.get('maintenanceperiod');
            objProduct.Lifespan_Months__c = (Integer) mapJson.get('lifespan');
            objProduct.Cost__c = (Decimal) mapJson.get('cost');
            objProduct.Warehouse_SKU__c = (String) mapJson.get('sku');
            objProduct.Current_Inventory__c = (Integer) mapJson.get('quantity');
            equipmentList.add(objProduct);
        }
        if(equipmentList.size() > 0){
            upsert equipmentList;
        }

    }


}